### ISSUE TITLE
Fix the README.md

### ISSUE THREAD

**Issue by DarwinGonzalez** [nestor-gm/AllIn#2]
I think that you mean: 
# All in
instead of 

> #All in

_#FIXTHISNOWTY_

**Comment by DarwinGonzalez** [comment]
_**Nice Job!**_

**Comment by fiaz-ali** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
you21979, @sarmel, @klihelp, @ironwill647, @ianpaschal, @bhalla98, @Geek4IT, @abc0xmattyic333, @Vextraaa, @xavierlupin, @irunthis13, @kevoj, @mul1sh, @AppServiceProvider, @iShawnWang, @ViniFreiri, @tristanperalta, @CHALLENG-CLG, @EmmaRamirez, @ArunkumarRamanan, @Skanislav, @Ayesh, @bbenzikry, @The-Gupta, @gregbook, @dvelikiy, @brajabi, @omar1326, @billyct, @Chippi, @JC1002, @matiasbenedetto, @sihaelov, @AyberkCakar, @edusta, @jaylabs, @karimhossenbux, @idaWHALE, @dividy, @aodin, @caiyue1993, @sunwaylive, @mikostel, @majkamajka, @wanoo21, @Ro5s, @vinzentvw, @azurechen, @jasonrobinson, @opt9
